### ISSUE TITLE
No listings for 3rd-party plugins

### ISSUE THREAD

**Issue by jelabarre59** [openmediavault/openmediavault-docs#128]
**Describe the improvement you'd like**
On the "Plugins" page for the OMV documentation, it lists the built-in plugins for OMV, but for 3rd-party plugins it refers to omv-extras.org.  However, all that site has is documentation on installing plugins, but no listing of available plugins.

There either needs to be a list of 3rd-party pluging on the OMV site, or a link to a site that actually has the 3rd-party plugins listed.

**Comment by ryecoaaron** [comment]
The System -> Plugins tab in the OMV web interface is self documenting and has all of the plugins.  Why is another site listing the plugins needed?  This is an omv-extras issue as well.  https://github.com/OpenMediaVault-Plugin-Developers/packages/issues

**Comment by jelabarre59** [comment]
Not much use AT ALL if you haven't set up OMV yet.

The purpose is to see if it's even worth setting up a server.  So I'd need a list of 3rd-party plugins *BEFORE HAND*, to see if it's even worth bothering with OMV.  Not much of an answer, and from what I see it's certainly not worth wasting my time setting it up only to find it doesn't do what I need.

**Comment by jelabarre59** [comment]
Oh, and your omv-extras issue is EMPTY

**Comment by ryecoaaron** [comment]
>  Not much of an answer,

I wasn't answering you.  I was telling you what was available now and I was serious when I asked why.  I added a full list with descriptions of all omv-extras plugins to the omv-extras start page right after you posted.  But since you are evidently irritated with my question, I guess you won't care.

> Oh, and your omv-extras issue is EMPTY

As expected.  I can't move your issue about omv-extras to the omv-extras issue tracker.  I was suggesting opening the issue in the relevant location.

**Comment by jelabarre59** [comment]
Nevermind, I'm trying out a different solution anyway.
