### ISSUE TITLE
doc-improvement: add openmediavault-backup to "new user" & "backup" sections

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#75]
OMV was reviewed on 8Feb2021 in a [German NAS forum ](https://www.elefacts.de/test-161-die_3_besten_nas_betriebssysteme_fuer_das_jahr_2021_im_ueberblick)
Based on feedback of tester & moderator of this forum the **incorrect understanding was** that OMV has no capability to backup OMV configuration but openmediavault-backup exists since a long time!

To fix this wrong conclusion documentation should be improved by adding openmediavault-backup to "new user" & "backup" sections

**Comment by mi-hol** [comment]
@votdev @ryecoaaron @flmaxey  is the [guide for using openmediavault-backup in the forum](https://forum.openmediavault.org/index.php?thread/5080-configuration-backup/&postID=44579#post44579) up-to-date so that we can add it to the official documentation?

**Comment by flmaxey** [comment]
Since that guide is from 2014 (6+ years old), I tend to think that it's probably out of date.  Since it references a 3rd party package (Clonezilla) there's no way to know if it still applies without testing.  

openmediavault-backup is one among a number of plugins that might benefit from a doc.  I just finished a plugin doc.  Time permitting, others are planned.

**Comment by PrplHaz4** [comment]
The Clonezilla guide is definitely outdated (it is now found on the "Kernel" page in OMV-Extras).  The default options on the "Backup" tab work well for simple cases and are mostly self-explanatory.

It would also make more sense (IMO) to refer to this as a "System Backup", since the general term "Backup" on a NAS OS is a bit ambiguous.

1. Install OMV-Extras
2. Install openmediavault-backup plugin
3. Go to "Backup" tab
4. Select a shared folder for the destination of your system backup image, then "Save"
5. Click "Add new scheduled backup job", and select frequency and notification options, then "Save"

![image](https://user-images.githubusercontent.com/841414/107828234-6e4bab80-6d56-11eb-91a8-b3a05b079cf7.png)

**Comment by ryecoaaron** [comment]
> Based on feedback of tester & moderator of this forum the incorrect understanding was that OMV has no capability to backup OMV configuration but openmediavault-backup exists since a long time!

They probably say that because everyone is so used to being able to download a config file on FreeNAS and restore a system from that config.  The backup plugin is really backing up the entire OS.

> It would also make more sense (IMO) to refer to this as a "System Backup"

I put it in the System section of the web interface to signify that it was a system backup.  If it was meant to backup data, it would have been in the Services section.  That said, the actual javascript file is called SystemBackup.js - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-backup/tree/master/var/www/openmediavault/js/omv/module/admin/system/backup - not that anyone sees that.
