### ISSUE TITLE
official 'installation' refers to 'several preconfigured images for ARM devices' that seem long obsolete => remove

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#87]
https://openmediavault.readthedocs.io/en/5.x/installation/index.html refers to 'several preconfigured images for ARM devices' that seem long obsolete.
Is my understanding correct?
If confirmed I'd replace it with 'an automated installation script'.
Please comment

**Comment by mi-hol** [comment]
@ryecoaaron I'm hoping for a comment from you

**Comment by ryecoaaron** [comment]
Yes, there are no preconfigured images anymore and the install script is the way to go.

**Comment by mi-hol** [comment]
@ryecoaaron is my [changed text proposal](https://github.com/mi-hol/openmediavault-docs/commit/c8b2d3b8a740f39a2272ae6533fb00f532fc8d10) correct?

**Comment by ryecoaaron** [comment]
It isn't wrong but the script works on any architecture not just arm.  So, if someone installs Debian on an amd64 machine because the OMV iso doesn't allow them to do X, they can run the install script to install OMV on that debian install.

**Comment by mi-hol** [comment]
@ryecoaaron @flmaxey  please have another look. 
I'm not satisfied with "low cost x86 architecture computers " myself yet, maybe you'd have a better suggestion?
  [ changed text proposal ](https://github.com/mi-hol/openmediavault-docs/blob/master/installation/index.rst)

**Comment by ryecoaaron** [comment]
The cost and architecture really have nothing to do with it.  So, i would something like "Recommend method for SBCs and alternate installs starting with Debian/Armbian".  I also really would only have two install variants:  one that uses the OMV iso and the other that uses the install script.  If the user installed Debian on an x86 system, it doesn't really matter if it is complex or advanced.

**Comment by flmaxey** [comment]
Referring to the previous version in the 5X branch:
- Cost has no place with architecture.  It wouldn't matter if the X86 was a 50 Euro workstation refurb or a 3000 Euro Server.
- It appears that Volker's idea of "installation variants" refers to the media used as the installation source (ISO, USB stick, netboot, etc.), not the platform.  You're also referencing experience level, in a section of the OMV wiki that's dedicated to advanced users.

Installation choices seem to be:
X86
1. ISO  (By CD, or USB thumbdrive.)
2. Debian install (by whatever means) followed by Aaron's one line script.

SBC
1. Rasp OS or Armbian, and Aaron' s script.
________________________________________________________________

Destination boot media seems to be:

X86
1. Hard drive
2. Something plugged into a USB port, thumbdrive, SSD, etc.

SBC
1. SD-card  (primarily)

Other items:
- There are no SBC images being maintained for SBC's.  That line and link references a doc that is out-of-date.
- While I know it's possible with some, I've never set up an SBC to boot from a USB port.  Most of them boot from SD-cards or on-board flash.  This reference:
**:doc:`USB flash drive </installation/on_usb>` - This installs |omv| to run from a USB flash drive.** 
should be moved from SBC to x86.  Otherwise, it would require a backing document that at least loosely outlines an SBC build onto a USB thumbdrive and identifies some of the more popular SBC models that can boot from USB ports.  That document doesn't exist.
- Volker's installation script is still backing the link for "installation on Debian" and the boot strap method is backed by a very old forum post. 

_________________________________________________________________________

Most of the above will mean deleting or editing currently linked documents, or creating new doc's to back the links.

**Comment by mi-hol** [comment]
> * You're also referencing experience level, in a section of the OMV wiki that's dedicated to advanced users.

actually from my view this section is the first "touchpoint" for all potential users of OMV. 
Will this change any of the comments made or trigger new comments?


Sorry I forgot to mention, that all references in the current version will be updated after we agreed on the content!
I've tried to incorporate your comments above in my draft proposal

> * This reference:
>   **:doc:`USB flash drive </installation/on_usb>` - This installs |omv| to run from a USB flash drive.**
>   should be moved from SBC to x86.  Otherwise, it would require a backing document

I'd propose to link this to content from your "new user" guide to avoid repeated & reduntant content.
Does this make sense?

> Volker's multi-line installation script is still backing the link for "installation on Debian" 
same proposal as above

> i would something like "Recommend method for SBCs and alternate installs starting with Debian/Armbian".

thanks, great suggestion, I amended wording slightly to "alternate installs starting with a hardware specific Debian OS image".
Is that ok?

**Comment by flmaxey** [comment]
Updating the items that are clearly out-of-date makes sense.

A note in that location, directing "Linux or NAS beginners" to the New User Guide, makes sense as well.  The somewhat terse install process(es) outlined  in the wiki's **Installation** section do not serve beginners well.

_______________

References to SBC's are another matter.  That is a topic you should run by Volker before working on it.  As I understand it, in the past, Volker  insisted on keeping SBC's, extra's plugins, etc., separate from the main project.  This is one of the reasons why the Extras plugin and omvextras.org, with it's own wiki and a small collection of SBC related documents, were created.  Including SBC's in the project's Wiki would be a change of policy.  

Again, this is my understand of things.  I might be wrong.

**Comment by mi-hol** [comment]
@votdev may I ask for your comment on below?
> References to SBC's are another matter. That is a topic you should run by Volker before working on it. As I understand it, in the past, Volker insisted on keeping SBC's, extra's plugins, etc., separate from the main project. This is one of the reasons why the Extras plugin and omvextras.org, with it's own wiki and a small collection of SBC related documents, were created. Including SBC's in the project's Wiki would be a change of policy.

**Comment by mi-hol** [comment]
ping @votdev

**Comment by mi-hol** [comment]
closed via https://github.com/openmediavault/openmediavault-docs/commit/64086d90f76a40f49c421328907f8d83e467fa73
