### ISSUE TITLE
change all depricated "/srv/dev-disk-by-label" to "/srv/dev-disk-by-UUID"

### ISSUE THREAD

**Issue by mi-hol** [openmediavault/openmediavault-docs#89]
obsolete content found in https://openmediavault.readthedocs.io/en/5.x/new_user_guide/newuserguide.html?highlight=rsync#full-disk-mirroring-backup-with-rsync likely more such incorrect references exist

@flmaxey could you please have a look?

**Comment by ryecoaaron** [comment]
Those are just paths and not really incorrect.  People with filesystems mounted before by-label was disabled could still be using a by-label path.  Some really old systems that have been upgraded might still be using /media/ mount points (I have a system like that).

**Comment by flmaxey** [comment]
Did you **not** see the note?  It's been in the Guide since shortly after Volker made the change:

Herewith:
_______
**As of OMV 5.5.20, data drives are mounted using UUID (Universally Unique Identifier). The path under the Mount Point will be similar to: /srv/dev-disk-by-uuid-f188c8ad-74d3-443a-a23e-89711270367d (This is an example only – all disks will have a unique identifier.) To avoid source and destination drive confusion when using UUID’s: The Mount Point Column, above, can be moved by “left clicking” the column head, holding and dragging it to the Devices and Label columns.**
_______

Also of significant note is that, at this point, the majority of the userbase is probably still on an OMV version prior to 5.5.20.  The guide serves the 5.X version, not the absolute latest sub-version of OMV 5.

You're reading one paragraph, without the full context, and "assuming" that something is wrong or missing.  And this is **not** the first time.  Stop pinging me on the 5.X guide until you actually read it.
